### ISSUE TITLE
'Could not find MAXScript Macro Recorder' in 3dsMax2017

### ISSUE THREAD

**Issue by Finetuned** [ycdivfx/YCDIVFX_MaxPlus#3]
I've configured maxconnect in PyCharm by duplicating 3dsmaxpy.exe as python.exe.
This resolves the issue as described on the [Autodesk forums
](https://forums.autodesk.com/t5/3ds-max-programming/pycharm-quot-3dsmaxpy-exe-gt-gt-not-a-valid-home-for-python-sdk/td-p/6794310)

The script mostly fails to find the mini listener except when using debug:

- running from the command line fails 100% of the time.
- running run.py works around 50% of the time.
- debugging run.py works 100% of the time

```Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "C:\Dev\bin\YCDIVFX_MaxPlus-master\packages\maxconnect\tomax.py", line 197, in _getWindows
    attachThreads(gMainWindow)
  File "C:\Dev\bin\YCDIVFX_MaxPlus-master\packages\maxconnect\tomax.py", line 176, in attachThreads
    thread = GetWindowThreadProcessId(hwnd, 0) #max thread
WindowsError: exception: access violation writing 0x00007FFF00000000
Could not find MAXScript Macro Recorder

Process finished with exit code 0
```

**Comment by Finetuned** [comment]
I traced the issue to attachThreads(hwnd) in packages/maxconnect/tomax.py and added:
```
  lpdw_process_id = ctypes.c_ulong()
``` 
then updated the second arg from 0 to:
```
   thread = GetWindowThreadProcessId(hwnd, ctypes.byref(lpdw_process_id)) #max thread
```
[ref](https://stackoverflow.com/questions/42938155/cant-get-processid-using-ctypes-windll-user32-getwindowthreadprocessid)
